# File PrGate
#
# Azure pipeline jobs template to ensure that the PR is ready to be merged.
#
# Copyright (C) Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
- name: build_matrix
  type: object

jobs:
  - ${{ each item in parameters.build_matrix }}:
    - job: TEST_${{ item.Key }}

      timeoutInMinutes: 15

      workspace:
        clean: all

      pool:
        vmImage: ${{ item.Value.vmImage }}

      ${{ if contains(item.Value.vmImage, 'ubuntu')}}:
        container:
          image: ${{ item.Value.containerImage }}
          options: --name mu_devops_build_container

      steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.10'
        inputs:
          versionSpec: '3.10.x'
          architecture: 'x64'

      - template: Steps/RustSetupSteps.yml@mu_devops

      - script: rustup component add clippy
        displayName: Install Clippy

      - script: cargo make build-std
        displayName: Build Target [Local OS]

      - script: cargo make build-x64
        displayName: Build Target [x86_64-unknown-uefi]

      - script: cargo make build-aarch64
        displayName: Build Target [aarch64-unknown-uefi]

      - script: cargo make test
        displayName: Run Tests

      - script: cargo clippy
        displayName: Run cargo clippy
        env:
          RUSTC_BOOTSTRAP: '1'

      - script: cargo fmt --check --all
        displayName: Run cargo fmt
        env:
          RUSTC_BOOTSTRAP: '1'
